# Generated by Django 2.2 on 2019-05-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190501_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='id',
            name='id_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
